repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^charts/.*/templates/

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c, .yamllint.yaml]
        exclude: ^charts/.*/templates/

  - repo: local
    hooks:
      - id: helm-lint
        name: helm lint
        entry: helm lint charts/knot-resolver
        language: system
        pass_filenames: false
        files: charts/knot-resolver/

      - id: helm-docs
        name: helm-docs
        entry: helm-docs --chart-search-root charts --sort-values-order file --ignore-non-descriptions
        language: system
        pass_filenames: false
        files: charts/knot-resolver/

      - id: kubeconform
        name: kubeconform
        entry: >-
          bash -c 'for f in charts/knot-resolver/ci/*.yaml; do
          helm template t charts/knot-resolver -f "$f" --set service.clusterIP=10.96.0.53
          | kubeconform -strict -summary -ignore-missing-schemas
          -kubernetes-version 1.30.0; done'
        language: system
        pass_filenames: false
        files: charts/knot-resolver/

      - id: trivy-config
        name: trivy config
        entry: >-
          trivy config --exit-code 1 --severity MEDIUM,HIGH,CRITICAL
          -c charts/knot-resolver/trivy.yaml
          --ignorefile charts/knot-resolver/.trivyignore
          charts/knot-resolver
        language: system
        pass_filenames: false
        files: charts/knot-resolver/
