{{- $managed := include "knot-resolver.managedConfig" . | fromYaml -}}
{{- $config := mustMergeOverwrite $managed (deepCopy .Values.configOverride) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knot-resolver.fullname" . }}
  labels:
    {{- include "knot-resolver.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml $config | nindent 4 }}
