{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knot-resolver.fullname" . }}-metrics
  labels:
    {{- include "knot-resolver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "knot-resolver.selectorLabels" . | nindent 4 }}
{{- end }}
