apiVersion: v1
kind: Service
metadata:
  name: {{ include "knot-resolver.fullname" . }}
  labels:
    {{- include "knot-resolver.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: dns
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: UDP
    - name: dns-tcp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "knot-resolver.selectorLabels" . | nindent 4 }}
