forwarding:
  kubeDNS:
    enabled: true

resolver:
  rebindingProtection: true
  serveStale: true
  dnssec: true
  logBogus: true
  glueChecking: normal
  violatorsWorkarounds: true
  timeJumpDetection: true

logging:
  level: info
  groups:
    - dnssec
    - cache

cache:
  sizeLimit: 128Mi
  ttlMin: 60s
  ttlMax: 86400s
  prefetchExpiring: true

configOverride:
  cache:
    prefetch:
      prediction: {}

replicaCount: 2

podDisruptionBudget:
  enabled: true
  minAvailable: 1
