forwarding:
  kubeDNS:
    enabled: true

resolver:
  rebindingProtection: true
  logBogus: true
  serveStale: true
  glueChecking: normal
  dnssec: true

logging:
  level: info

cache:
  sizeLimit: 128Mi
  ttlMin: 60
  ttlMax: 86400
  prefetchExpiring: true
  prefetchPrediction: true

replicaCount: 2

podDisruptionBudget:
  enabled: true
  minAvailable: 1
